# Generated by Django 5.2.5 on 2025-08-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=16, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("rides_left", models.IntegerField(default=5)),
                ("random_num", models.CharField(max_length=16)),
                ("checksum", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("random_num_at_time", models.CharField(max_length=16)),
                ("rides_left_at_time", models.IntegerField()),
                ("bus_line", models.CharField(max_length=10)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="main.card",
                    ),
                ),
            ],
        ),
    ]
