# Generated by Django 5.2.5 on 2025-08-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="blacklisted",
            field=models.BooleanField(default=False),
        ),
    ]
